# Generated by Django 2.2.12 on 2022-11-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(null=True)),
                ('exam_time_start', models.TimeField(null=True)),
                ('exam_time_end', models.TimeField(null=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Class')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Student')),
            ],
        ),
    ]
