# Generated by Django 2.2.12 on 2022-11-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_addexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexam',
            name='student',
        ),
        migrations.AddField(
            model_name='addexam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Teacher'),
        ),
    ]
