# Generated by Django 2.2.12 on 2022-11-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='current_answer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
