# Generated by Django 2.2.12 on 2022-11-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_questionbank_current_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='current_answer',
            field=models.CharField(max_length=50),
        ),
    ]
