# Generated by Django 2.2.12 on 2022-11-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_auto_20221124_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='question_id',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
