# Generated by Django 2.2.12 on 2022-11-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20221124_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.ManyToManyField(to='info.QuestionBank')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Teacher')),
            ],
        ),
    ]
