# Generated by Django 2.2.12 on 2022-11-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.AddExam'),
            preserve_default=False,
        ),
    ]
