# Generated by Django 2.2.12 on 2022-11-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_paper_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='mark_format',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='marks',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
