# Generated by Django 2.2.12 on 2022-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_auto_20221128_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='mark_format',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='marks',
            field=models.IntegerField(editable=False),
        ),
    ]
