# Generated by Django 2.2.12 on 2022-11-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_auto_20221128_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='mark_format',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
