# Generated by Django 2.2.12 on 2022-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_result_each_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='each_mark',
        ),
        migrations.AddField(
            model_name='paper',
            name='each_mark',
            field=models.ManyToManyField(null=True, related_name='_paper_each_mark_+', to='info.paper'),
        ),
    ]
