# Generated by Django 2.2.12 on 2022-11-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_remove_paper_each_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='eachexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.AddExam')),
                ('Paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.paper')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.QuestionBank')),
            ],
        ),
    ]
