# Generated by Django 2.2.12 on 2022-11-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_eachexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eachexam',
            name='Paper',
        ),
        migrations.AddField(
            model_name='eachexam',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eachexam',
            name='total',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
