# Generated by Django 2.2.12 on 2022-12-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0036_result_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='signature_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Signature ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=254, null=True, verbose_name='Payment Status'),
        ),
    ]
