# Generated by Django 2.2.12 on 2022-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0037_auto_20221206_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.FloatField(blank=True, default=15000, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='Failure', max_length=254, null=True, verbose_name='Payment Status'),
        ),
    ]
