# Generated by Django 2.2.12 on 2022-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0038_auto_20221207_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='fees',
            field=models.FloatField(blank=True, default=150000, null=True, verbose_name='Amount'),
        ),
    ]
