# Generated by Django 2.2.12 on 2022-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0040_class_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
